### ISSUE TITLE
please include license files for Apache-2.0 and MIT licenses

### ISSUE THREAD

**Issue by decathorpe** [Gankra/backtrace-ext#1]
Both the Apache-2.0 and MIT licenses require that redistributed sources contain a copy of the license text. This applies to crates that are redistributed via crates.io, to any places where this crate's source code ends up in vendor tarballs for Rust applications, and to packages of this crate for Linux Distributions.

**Comment by Gankra** [comment]
done

**Comment by decathorpe** [comment]
Great, thank you!
